const secretsmanager = require('aws-cdk-lib/aws-secretsmanager');
const { Construct } = require('constructs');

/**
 * SecretsConstruct — provisions the two per-component HS256 JWT signing
 * secrets in AWS Secrets Manager (ADR 0006).
 *
 * Design notes:
 *
 * - Two secrets, one per minter. The agent (`travel-agent`) and the
 *   poller (`trip-tracker-poller`) each sign with their OWN secret and
 *   present their OWN `sub`. The verifier (the shared MCP authorizer +
 *   both MCP server handlers) checks the token against whichever secret
 *   matches AND couples each secret to its allowed `sub`. A compromised
 *   poller secret therefore cannot mint agent-claiming tokens. This
 *   replaces the single hard-coded shared signing literal that anyone
 *   with repo access could previously forge against.
 *
 * - Values are generated by CloudFormation at deploy time via
 *   `generateSecretString` — never pre-provisioned, never in the repo.
 *   Random generation is the right shape for an HMAC secret (unlike the
 *   SES verified identity, which is a manual console step because email
 *   verification needs a received message).
 *
 * - 40 alphanumeric characters, punctuation excluded. Long enough for an
 *   HS256 key; punctuation-free keeps the value safe to inject as a
 *   plain Lambda env-resolved string with no escaping concerns.
 *
 * - Rotation is manual in v1 (no rotation Lambda). The rotation
 *   procedure is documented in ADR 0006's Consequences section. A
 *   rotation Lambda must coordinate minter + verifier rollover and is
 *   out of scope for this change.
 *
 * - Grants are issued by the consuming constructs via `grantRead`, not
 *   here. This construct only owns secret creation; each consumer scopes
 *   its own least-privilege `secretsmanager:GetSecretValue` to the
 *   specific secret ARN it needs.
 *
 * Exposes `this.agentJwtSecret` and `this.pollerJwtSecret` as
 * `secretsmanager.Secret` instances for the stack to pass into the
 * agent / poller / MCP-server constructs.
 */
class SecretsConstruct extends Construct {
    constructor(scope, id, props) {
        super(scope, id, props);

        const generateSecretString = {
            passwordLength: 40,
            excludePunctuation: true,
            includeSpace: false,
        };

        this.agentJwtSecret = new secretsmanager.Secret(this, 'AgentJwtSigner', {
            secretName: 'trip-tracker-agent-jwt-signer',
            description: 'HS256 signing secret for agent-minted MCP JWTs (sub=travel-agent). ADR 0006.',
            generateSecretString,
        });

        this.pollerJwtSecret = new secretsmanager.Secret(this, 'PollerJwtSigner', {
            secretName: 'trip-tracker-poller-jwt-signer',
            description: 'HS256 signing secret for poller-minted MCP JWTs (sub=trip-tracker-poller). ADR 0006.',
            generateSecretString,
        });
    }
}

module.exports = SecretsConstruct;
